- name: Backup Current Configuration for {{ inventory_hostname }} {{ ansible_date_time.iso8601 }}
  junos_config:
    backup: yes
    provider: "{{ creds }}"

# Single interface tasks
- name: Clear interface {{ junos_interface_name }}
  junos_interface:
    name: "{{ junos_interface_name }}"
    state: absent
    active: False
    provider: "{{ creds }}"
  when: (junos_interface_agg == 'disabled' and junos_interface_w_clear == 'enabled')

- name: configure interface {{ junos_interface_name }}
  junos_interface:
    name: "{{ junos_interface_name }}"
    description: "{{ junos_interface_desc }}"
    state: "{{ junos_interface_state }}"
    active: "{{ junos_interface_active }}"
    provider: "{{ creds }}"
  when: (junos_interface_agg == 'disabled' and junos_interface_build == 'enabled')

# Aggregate tasks
- name: Multiple interface Addition variables 
  include_vars: vars/task_vars/jun_int_aggregate.yml
  when: junos_interface_agg == 'enabled'

- name: Aggregate interface clear
  junos_interface:
    aggregate:
      - { name: "{{ agg_junos_interface_name1 }}", description: "{{ agg_junos_interface_desc1 }}"}
      - { name: "{{ agg_junos_interface_name2 }}", description: "{{ agg_junos_interface_desc2 }}"}
    state: absent
    active: False
    provider: "{{ creds }}"
  when: (junos_interface_agg == 'enabled' and agg_junos_interface_w_clear == 'enabled')

- name: Aggregate interface add
  junos_interface:
    aggregate:
      - { name: "{{ agg_junos_interface_name1 }}", description: "{{ agg_junos_interface_desc1 }}", state: "{{ junos_interface_state }}", active: "{{ junos_interface_active }}"}
      - { name: "{{ agg_junos_interface_name2 }}", description: "{{ agg_junos_interface_desc2 }}", state: "{{ junos_interface_state }}", active: "{{ junos_interface_active }}"}
    provider: "{{ creds }}"
  when: (junos_interface_agg == 'enabled' and agg_junos_interface_build == 'enabled')

- name: confirm a previous commit for {{ inventory_hostname }} Timestamp - {{ ansible_date_time.iso8601 }}
  junos_config:
    confirm_commit: yes
    comment: "{{ task_comment }}"
    provider: "{{ creds }}"

- name: Commit Message
  debug: msg="{{ task_comment }}"
