- name: Backup Current Configuration for {{ inventory_hostname }} {{ ansible_date_time.iso8601 }}
  junos_config:
    backup: yes
    provider: "{{ creds }}"

# Single interface tasks
- name: Clear interface {{ junos_l3_interface_name }}
  junos_interface:
    name: "{{ junos_l3_interface_name }}"
    state: absent
    active: False
    provider: "{{ creds }}"
  when: (junos_l3_interface_agg == 'disabled' and junos_l3_interface_w_clear == 'enabled')

- name: configure interface {{ junos_interface_name }}
  junos_interface:
    name: "{{ junos_l3_interface_name}}"
    description: "{{ junos_l3_interface_desc }}"
    state: "{{ junos_interface_state }}"
    active: "{{ junos_interface_active }}"
    provider: "{{ creds }}"
  when: (junos_l3_interface_agg == 'disabled' and junos_l3_interface_build == 'enabled')

- name: configure interface {{ junos_l3_interface_name }} with IP - {{ junos_l3_interface_ipv4 }}
  junos_l3_interface:
    name: "{{ junos_l3_interface_name }}"
    ipv4: "{{ junos_l3_interface_ipv4 }}"
    provider: "{{ creds }}"
  when: (junos_l3_interface_agg == 'disabled' and junos_l3_interface_build == 'enabled' and junos_l3_dual_stack == 'disabled')

- name: configure interface {{ junos_l3_interface_name }} with IP - {{ junos_l3_interface_ipv4 }} and {{ junos_l3_interface_ipv6 }}
  junos_l3_interface:
    name: "{{ junos_l3_interface_name }}"
    ipv4: "{{ junos_l3_interface_ipv4 }}"
    ipv6: "{{ junos_l3_interface_ipv6 }}"
    provider: "{{ creds }}"
  when: (junos_l3_interface_agg == 'disabled' and junos_l3_interface_build == 'enabled' and junos_l3_dual_stack == 'enabled')

# Aggregate tasks
- name: Multiple interface Addition variables 
  include_vars: vars/task_vars/jun_l3_int_aggregate.yml
  when: junos_l3_interface_agg == 'enabled'

- name: Clear aggregate interfaces
  junos_interface:
    aggregate:
      - name: "{{ agg_junos_l3_interface_name1 }}"
      - name: "{{ agg_junos_l3_interface_name2 }}"
    state: absent
    active: False
    provider: "{{ creds }}"
  when: (junos_l3_interface_agg == 'enabled' and agg_junos_l3_interface_w_clear == 'enabled')

- name: Aggregate interface add
  junos_interface:
    aggregate:
      - { name: "{{ agg_junos_l3_interface_name1 }}", description: "{{ agg_junos_l3_interface_desc1 }}", state: "{{ junos_interface_state }}", active: "{{ junos_interface_active }}"}
      - { name: "{{ agg_junos_l3_interface_name2 }}", description: "{{ agg_junos_l3_interface_desc2 }}", state: "{{ junos_interface_state }}", active: "{{ junos_interface_active }}"}
    provider: "{{ creds }}"
  when: (junos_l3_interface_agg == 'enabled' and agg_junos_l3_interface_build == 'enabled')

- name: Aggregate interface add ipv4
  junos_l3_interface:
    aggregate:
      - { name: "{{ agg_junos_l3_interface_name1 }}", ipv4: "{{ agg_junos_l3_interface_ipv4_1 }}"}
      - { name: "{{ agg_junos_l3_interface_name2 }}", ipv4: "{{ agg_junos_l3_interface_ipv4_2 }}"}
    provider: "{{ creds }}"
  when: (junos_l3_interface_agg == 'enabled' and agg_junos_l3_interface_build == 'enabled' and agg_junos_l3_dual_stack == 'disabled')

- name: Aggregate interface add ipv4 and ipv6
  junos_l3_interface:
    aggregate:
      - { name: "{{ agg_junos_l3_interface_name1 }}", ipv4: "{{ agg_junos_l3_interface_ipv4_1 }}", ipv6: "{{ agg_junos_l3_interface_ipv6_1 }}"}
      - { name: "{{ agg_junos_l3_interface_name2 }}", ipv4: "{{ agg_junos_l3_interface_ipv4_2 }}", ipv6: "{{ agg_junos_l3_interface_ipv6_2 }}"}
    provider: "{{ creds }}"
  when: (junos_l3_interface_agg == 'enabled' and agg_junos_l3_interface_build == 'enabled' and agg_junos_l3_dual_stack == 'enabled')

- name: confirm a previous commit for {{ inventory_hostname }} Timestamp - {{ ansible_date_time.iso8601 }}
  junos_config:
    confirm_commit: yes
    comment: "{{ task_comment }}"
    provider: "{{ creds }}"

- name: Commit Message
  debug: msg="{{ task_comment }}"
