- name: Backup Current Configuration for {{ inventory_hostname }} {{ ansible_date_time.iso8601 }}
  junos_config:
    backup: yes
    provider: "{{ creds }}"

- name: Archive older configs
  shell: /bin/cp config_partial/basic_ibgp/ibgp-{{ inventory_hostname }}.cfg archive/ibgp-{{ inventory_hostname }}-{{ ansible_date_time.iso8601 }}.cfg

- name: Archive older configs
  shell: /bin/rm config_partial/basic_ibgp/ibgp-{{ inventory_hostname }}.cfg

- name: Generate Basic iBGP Configuration File
  template: src=templates/basic_ibgp.j2 dest=config_partial/basic_ibgp/ibgp-{{ inventory_hostname }}.cfg
  with_items: "{{ basic_ibgp }}"

- name: Merge configuration via napalm_install_config
  napalm_install_config:
    hostname: "{{ inventory_hostname }}"
    config_file: config_partial/basic_ibgp/ibgp-{{ inventory_hostname }}.cfg
    dev_os: junos
    replace_config: false
    commit_changes: True
    provider: "{{ creds }}"

- name: confirm a previous commit for {{ inventory_hostname }} Timestamp - {{ ansible_date_time.iso8601 }}
  junos_config:
    confirm_commit: yes
    comment: "{{ task_comment }}"
    provider: "{{ creds }}"

- name: Commit Message
  debug: msg="{{ task_comment }}"
