- name: Backup Current Configuration for {{ inventory_hostname }} {{ ansible_date_time.iso8601 }}
  junos_config:
    backup: yes
    provider: "{{ creds }}"

- name: Clear DNS and Hostname
  junos_system:
    domain_name:
    domain_search:
    name_servers:
    state: absent
    provider: "{{ creds }}"

- name: configure hostname and domain name {{ junos_system_hostname }}.{{ junos_system_domain_name }}
  junos_system:
    hostname: "{{ junos_system_hostname }}"
    domain_name: "{{ junos_system_domain_name }}"
    state: present
    provider: "{{ creds }}"

- name: Configure DNS Domains
  junos_system:
    domain_search:
      - "{{ dns_dom_1 }}"
      - "{{ dns_dom_2 }}"
      - "{{ dns_dom_3 }}"
    state: present
    provider: "{{ creds }}"

- name: Configure DNS Servers for {{ inventory_hostname }}
  junos_system:
    name_servers:
      - "{{ name_server_1 }}"
      - "{{ name_server_2 }}"
      - "{{ name_server_3 }}"
    state: present
    provider: "{{ creds }}"

- name: confirm a previous commit for {{ inventory_hostname }} Timestamp - {{ ansible_date_time.iso8601 }}
  junos_config:
    confirm_commit: yes
    comment: "{{ task_comment }}"
    provider: "{{ creds }}"

- name: Commit Message
  debug: msg="{{ task_comment }}"
